name: Java Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main   # Trigger only on PRs targeting the main branch

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: mvn checkstyle:check

  spotbugs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Run SpotBugs
        run: mvn spotbugs:check

  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Verify Code Format
        run: mvn spotless:check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: mvn test

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Compile all Java files
        run: |
          mkdir -p bin
          javac -d bin $(find . -name "*.java")

  run-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Run main class
        run: |
          mkdir -p out
          javac -d out $(find src -name "*.java")
          java -cp out your.package.MainClass || true
