name: Java Compile Check

on:
  pull_request:
    branches:
      - main   # Trigger only on PRs targeting the main branch

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile all Java files
        run: |
          mkdir -p bin
          javac -d bin $(find . -name "*.java")
